<?php
/**
 * Created by PhpStorm.
 * User: alexey
 * Date: 09.04.2018
 * Time: 22:40
 */

namespace DB;


class DB extends \mysqli
{
    const STATIC_HOST="";
    const STATIC_USER="";
    const STATIC_PASSWD="";



    private $host;
    private $username;
    private $passwd;
    private $dbname;

    private $connected=false;


    public function __construct(string $host, string $username, string $passwd, string $dbname)
    {
        parent::__construct();
    }

    private static $_db=null;

    static public function GetStaticDB(){
        if(self::$_db==null){
            self::$_db=new DB();
        }
    }

    private function PrivateConnect()
    {
        if(!$this->connected) {
            parent::connect($this->host, $this->username, $this->passwd, $this->dbname);
            parent::autocommit(false);
            parent::set_charset("utf8");
        }
    }



    /**
     * @param string $query
     * @param int $resultmode
     * @return bool|\mysqli_result
     */
    public function query($query, $resultmode = MYSQLI_STORE_RESULT)
    {
        $this->PrivateConnect();
        return parent::query($query, $resultmode);
    }

    public function prepare($query)
    {
        $this->PrivateConnect();
        return new DBStatement( parent::prepare($query)); // TODO: Change the autogenerated stub
    }


    public function close()
    {
        if($this->connected) {
            parent::close(); // TODO: Change the autogenerated stub
        }
        $this->connected=false;
    }


}

class DBStatement{
    /** @var \mysqli_stmt */
    private $statement;

    function __construct(\mysqli_stmt $statement)
    {
        $this->statement=$statement;
    }

    /**
     * @param array ...$params
     * @return $this
     */
    function BindParam(...$params){
        call_user_func_array([$this->statement,"bind_param"],$params);
        return $this;
    }

    function Exec(){
        $this->statement->execute();
        return $this;
    }

    function GetResult(){
        return $this->statement->get_result();
    }
}